###################################################################################################################################################
#  _______  _       _________ _______  _______  _        _______  _______  _______  _______  _       __________________ _______  _       _______  #
# (  ___  )( (    /|\__   __/(       )(  ___  )( \      (  ____ \(  ____ \(  ____ \(  ____ \( (    /|\__   __/\__   __/(  ___  )( \     (  ____ \ #
# | (   ) ||  \  ( |   ) (   | () () || (   ) || (      | (    \/| (    \/| (    \/| (    \/|  \  ( |   ) (      ) (   | (   ) || (     | (    \/ #
# | (___) ||   \ | |   | |   | || || || (___) || |      | (__    | (_____ | (_____ | (__    |   \ | |   | |      | |   | (___) || |     | (_____  #
# |  ___  || (\ \) |   | |   | |(_)| ||  ___  || |      |  __)   (_____  )(_____  )|  __)   | (\ \) |   | |      | |   |  ___  || |     (_____  ) #
# | (   ) || | \   |   | |   | |   | || (   ) || |      | (            ) |      ) || (      | | \   |   | |      | |   | (   ) || |           ) | #
# | )   ( || )  \  |___) (___| )   ( || )   ( || (____/\| (____/\/\____) |/\____) || (____/\| )  \  |   | |   ___) (___| )   ( || (____/Y\____) | #
# |/     \||/    )_)\_______/|/     \||/     \|(_______/(_______/\_______)\_______)(_______/|/    )_)   )_(   \_______/|/     \|(_______|_______) #
# ----------------------------------------------------------------------------------------------------------------------------------------------- #
#                                           Made by bl4ckscor3 (Developer) & JustRamon (Creative Mind)                                            #
###################################################################################################################################################

#This value defines wether the user needs to have a nametag in their inventory when using /ae name on an animal. (Not effective in creative mode)
shouldNamingUseNametag: true

#When this is set to true, users will be able to issue multiple AnimalEssentials commands at a time.
#When set to false, it prevents users from, for instance, killing and naming their animal at the same time.
allowMultipleCommands: false

#Options for the update checker
update:

  #This option disables the plugin when set to true and an update has been found. When set to false, only an update notifier will show up if "check" is enabled.
  force: true

  #When set to false, the plugin will not check for updates.
  check: true
  
#Options for /ae find
find:

  #When this option is enabled, only animals owned by the command sender are displayed. When disabled, untamed animals will also show.
  onlyOwnAnimals: false
  
  #This option allows users to click the coordinates and teleport to the animal.
  #NOTE: You need to set the permission "aess.aetp". Without it, teleporting will not work, even if this value is set to true
  allowUsersToTp: true
  
  #This is the keyword used to determine wether the command is coming from clicking the chat, or from actually inputting the command into the chat.
  #It basically disabled users from using /aetp as a normal teleport command.
  #You can change this to anything, and it will still work. Think of it as a password needed to execute the command.
  keyword: comesFromLink
