name: AnimalEssentials
main: tk.justramon.animalessentials.core.AnimalEssentials
version: 0.1.0
author: [JustRamon, bl4ckscor3]
description: Several animal essentials such as renaming/teleporting and many others!
commands:
    animalessentials:
        description: Main command.
        usage: /<command>
        aliases: [ae, animaless, aess]
        
permissions:
    aess.*:
        description: Gives acces to all commands of AnimalEssentials.
        children:
          aess.reload: true
          aess.help: true
          aess.teleport: true
          aess.home.set: true
          aess.home.edit: true
          aess.home.delete: true
          aess.home.list: true
          aess.name: true
          aess.find: true
          aess.kill: true
          aess.heal: true
          aess.owner: true
          aess.tame: true
          aess.spawn: true
        default: op
    aess.home.*:
        description: Gives access to all home commands.
        children:
          aess.home.set: true
          aess.home.edit: true
          aess.home.delete: true
          aess.home.list: true
    aess.reload:
        description: Permission to reload the configuration.
    aess.help:
        description: Permission to show the help menu and help for commands.
    aess.teleport:
        description: Permission to teleport the right-clicked animal to the specified home or player. Poof!
    aess.home.set:
        description: Permission to set the home in the current world with the current coordinates.
    aess.home.edit:
        description: Permission to edit an existing home.
    aess.home.delete:
        description: Permission to get rid of an existing home.
    aess.home.list:
        description: Permission to list all available homes.
    aess.name:
        description: Permission to name the right-clicked animal.
    aess.find:
        description: Permission to find an animal with the given name.
    aess.kill:
        description: Permission to kill the right-clicked animal.
    aess.heal:
        description: Permission to heal the right-clicked animal.
    aess.owner:
        description: Permission to show the owner of the right-clicked animal.
    aess.tame:
        description: Permission to tame the right-clicked animal.
    aess.spawn:
        description: Permission to spawn an animal using the GUI.
