name: AnimalEssentials
main: tk.justramon.animalessentials.core.AnimalEssentials
version: 0.1
author: [JustRamon, bl4ckscor3]
description: Several animal essentials such as renaming/teleporting and many others!
commands:
    animalessentials:
        description: Main command.
        usage: /<command>
        aliases: [ae, animaless, aess]
        
permissions:
    aess.*:
        description: Gives acces to all commands of AnimalEssentials.
        children:
          aess.reload: true
          aess.help: true
          aess.teleport: true
          aess.home.set: true
          aess.home.edit: true
          aess.home.delete: true
          aess.home.list: true
          aess.name: true
          aess.find: true
        default: op
    aess.home.*:
        description: Gives access to all home commands.
        children:
          aess.home.set: true
          aess.home.edit: true
          aess.home.delete: true
          aess.home.list: true
    aess.reload:
        description: Permission to reload the configuration.
    aess.help:
        description: Permission to show the help menu and help for commands.
    aess.teleport:
        description: Permission to teleport an animal to the specified home or player. Poof!
    aess.home.set:
        description: Permission to set the home in the current world with the current coordinates.
    aess.home.edit:
        description: Permission to edit an existing home.
    aess.home.delete:
        description: Permission to get rid of an existing home.
    aess.home.list:
        description: Permission to list all available homes.
    aess.name:
        description: Permission to name an animal.
    aess.find:
        description: Finds an animal with the given name.
